feat: Add Broker JWT sync
bcgov-nr/nr-broker pull request #248
Opened 2024-08-21 23:07 UTC by GraceRuan

Add Broker JWT sync

2024-08-21 23:32 UTC, mbystedt requested changes

2024-08-21 23:32 UTC, mbystedt commented on package.json
> +    "libsodium-wrappers": "^0.7.15",
Unnecessary package as it duplicates the crypto built-in library

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.controller.spec.ts
> +});
Remove file

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.controller.ts
> +}
Remove file

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.service.ts
> +        };
Ignore event if environment is not tools.

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.service.ts
> +        const value = kvData[`broker-jwt:${clientId}`];
Loop over all keys and sync all values.

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.service.ts
> +        if (scmUrl) {
Check if scmUrl is GitHub. Bonus points if it checks the org and if the GitHub app has access.

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.service.ts
> +          const secretName = 'BROKER_JWT';
Keep same name from vault.

2024-08-21 23:32 UTC, mbystedt commented on src/github/github.service.ts
> +      await sodium.ready;
convert to builtin crypto library. Hint! chagtpt is your friend:
rewrite using nodejs api: const encryptedUint8Array = sodium.crypto_box_seal(secretUint8Array, publicKeyUint8Array);

2024-08-21 23:32 UTC, mbystedt commented on src/vault/vault.service.ts
> +        throw new Error('No data found at the specified path');
throw more specific error

2024-08-21 23:32 UTC, mbystedt commented on src/vault/vault.service.ts
> +    } catch (error) {
errors should only be caught by caller. Unnecessary try/catch

2024-09-05 21:20 UTC, closed without merging

2024-09-05 21:20 UTC, GraceRuan commented
Will be created in a new branch